server:
    port: 8080

spring:
    application:
        name: Vistora
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ecommerce
        username: root
        password: Mterstegen#1